spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: ${DATABASE_URL_DEV}
    username: ${DATABASE_USER_DEV}
    password: ${DATABASE_PASS}

  jpa:
    hibernate:
      ddl-auto: validate