name: CI/CD

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: 'maven'
      - name: Run Tests
        run: mvn -B test

  deploy:
    runs-on: ubuntu-22.04
    steps:

      #     Build Docker image:
      - uses: actions/checkout@v4
      - name: Build and tag image
        run: |
          docker build -t megoru/noticeme .
      #     Login to Docker Hub:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #     Push image to Docker Hub:
      - name: Publish image
        run: docker push megoru/noticeme