name: CI/CD

on:
  push:
    branches:
      - 'main'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '20'
      #     Run Tests:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: mvn -B test

      # Загрузка исходного кода:
      - uses: actions/checkout@v2

      # Сборка и тегирование Docker-образа:
      - name: Build and tag image
        run: |
          docker build -t docker.megoru.ru/notice-me-bot .

      # Вход в Docker Registry:
      - name: Docker login
        run: docker login docker.megoru.ru -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Отправка образа в Docker Registry:
      - name: Publish image
        run: docker push docker.megoru.ru/notice-me-bot:latest