name: CI/CD

on:
  push:
    branches:
      - 'main'

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:

      #     Run Tests:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Run Tests
        run: mvn -B test

      #     Build Docker image:
      - uses: actions/checkout@v2
      - name: Build and tag image
        run: |
          docker build -t megoru/noticeme .
      #     Login to Docker Hub:
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #     Push image to Docker Hub:
      - name: Publish image
        run: docker push megoru/noticeme