name: CI/CD

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '20'
          distribution: 'oracle'
          cache: 'maven'
      - name: Run Tests
        run: mvn -B test

  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '20'
          distribution: 'oracle'
          cache: 'maven'
      - name: Docker login and push
        run: |
          docker login docker.megoru.ru -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t docker.megoru.ru/notice-me-bot:latest .
          docker push docker.megoru.ru/notice-me-bot:latest